# SwiftLint configuration for CLARITY Pulse
# Updated for Swift 6.1 with strict concurrency checks

# Paths
included:
  - clarity-loop-frontend-v2
  - clarity-loop-frontend-v2Tests
  - clarity-loop-frontend-v2UITests

excluded:
  - DerivedData
  - .build
  - .swiftpm
  - Pods
  - Carthage
  - clarity-loop-frontend-v2/Core/Services/CognitoAuthService.swift.disabled
  - clarity-loop-frontend-v2/Core/Services/CognitoConfiguration.swift.disabled

# Rules
disabled_rules:
  - todo
  - line_length
  - type_body_length
  - file_length
  - force_cast
  - force_try

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Configuration
analyzer_rules:
  - unused_import
  - unused_declaration

cyclomatic_complexity:
  warning: 15
  error: 20

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID
    - URL
    - API

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - url
    - api
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level: 2
  function_level: 2

vertical_whitespace:
  max_empty_lines: 2

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Custom rules
custom_rules:
  no_print_statements:
    name: "Print Statement"
    regex: '(?<!\\\\)print\('
    message: "Print statements should be replaced with proper logging"
    severity: warning
    excluded:
      - "DummyAuthService"
      - "DummyHealthDataRepository"
      - "DummyInsightsRepository"
      - "DummyUserRepository"
      - "DummyHealthKitService"
      - "DummyAPIClient"

  no_force_unwrapping:
    name: "Force Unwrapping"
    regex: '(?<!\!)!\s*(?!as|try)'
    message: "Force unwrapping should be avoided. Use guard let or if let instead."
    severity: warning

  mark_format:
    name: "MARK Format"
    regex: '\/\/\s*MARK:\s*(?!-\s)'
    message: "MARK comments should include a hyphen after the colon (// MARK: - Section)"
    severity: warning

  todo_format:
    name: "TODO Format"
    regex: '\/\/\s*TODO(?!:)'
    message: "TODO comments should include a colon (// TODO: Description)"
    severity: warning
  
  no_phi_in_logs:
    name: "PHI in Logs"
    regex: '(log|print|debugPrint|NSLog|os_log).*\b(patient|health|medical|diagnosis|treatment|medication|blood|heart|glucose|weight|height|bmi)\b'
    message: "HIPAA: Do not log PHI (Protected Health Information)"
    severity: error
  
  private_by_default:
    name: "Private by Default"
    regex: '^(internal|public|open)\s+(let|var|func|class|struct|enum)'
    message: "Use private by default for access control"
    severity: warning
    
  no_hardcoded_secrets:
    name: "Hardcoded Secrets"
    regex: '(apiKey|api_key|secret|password|token)\s*=\s*"[^"]+"'
    message: "Never hardcode secrets in source code"
    severity: error

# Reporter
reporter: "xcode"