# SwiftLint configuration for CLARITY Pulse V2

# Paths to include
included:
  - clarity-loop-frontend-v2
  - clarity-loop-frontend-v2Tests
  - clarity-loop-frontend-v2UITests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Pods
  - Package.swift
  - clarity-loop-frontend-v2/Generated

# Rules configuration
disabled_rules:
  - trailing_whitespace # Disabled as per task requirement
  - identifier_name # Allow short names for TDD
  - force_cast # Sometimes needed for legacy code
  - force_try # Sometimes needed in tests

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - first_where
  - last_where
  - multiline_parameters
  - operator_usage_whitespace
  - redundant_type_annotation

# Rule parameters
line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 600

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 10

type_name:
  min_length: 2
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8