name: ClarityPulseWrapper
options:
  bundleIdPrefix: com.clarity
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  
targets:
  ClarityPulseWrapper:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "*.swift"
        excludes:
          - "*.json"
    resources:
      - Assets.xcassets
    postBuildScripts:
      - script: |
          echo "Copying amplifyconfiguration.json to Resources"
          cp "${SRCROOT}/amplifyconfiguration.json" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/"
        name: "Copy amplifyconfiguration.json"
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/amplifyconfiguration.json"
    dependencies:
      - package: ClarityPulse
        product: ClarityUI
      - package: ClarityPulse
        product: ClarityCore
      - package: ClarityPulse  
        product: ClarityDomain
      - package: ClarityPulse
        product: ClarityData
      - package: Amplify
        product: Amplify
      - package: Amplify
        product: AWSCognitoAuthPlugin
      - package: Amplify
        product: AWSAPIPlugin
    settings:
      INFOPLIST_FILE: Info.plist
      INFOPLIST_KEY_CFBundleDisplayName: "CLARITY Pulse"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: HJ7W9PTAD8
      PRODUCT_BUNDLE_IDENTIFIER: com.clarity.ClarityPulseWrapper
  
  ClarityPulseWrapperUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - ../clarity-loop-frontend-v2UITests
    dependencies:
      - target: ClarityPulseWrapper
    settings:
      GENERATE_INFOPLIST_FILE: true
      TEST_TARGET_NAME: ClarityPulseWrapper
      
packages:
  ClarityPulse:
    path: ../
  Amplify:
    url: https://github.com/aws-amplify/amplify-swift.git
    from: 2.48.1