name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  XCODE_VERSION: '16.0'
  IOS_VERSION: '18.0'
  SCHEME: 'ClarityPulse'

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint --reporter github-actions-logging

  test:
    name: Test
    runs-on: macos-latest
    needs: lint
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme "${{ env.SCHEME }}" \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,OS=${{ env.IOS_VERSION }},name=iPhone 16 Pro" \
          -enableCodeCoverage YES \
          clean test | xcpretty --test
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true

  build:
    name: Build
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
    
    - name: Build for Release
      run: |
        xcodebuild build \
          -scheme "${{ env.SCHEME }}" \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty